# Generated by Django 4.2.4 on 2023-08-24 18:54

import applications.music.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.PositiveIntegerField(validators=[applications.music.validators.validate_past_year], verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'исполнитель',
                'verbose_name_plural': 'исполнители',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
            },
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_position', models.PositiveIntegerField(verbose_name='Порядковый номер песни в альбоме')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='music.album', verbose_name='Альбом')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='music.track', verbose_name='Песня')),
            ],
            options={
                'unique_together': {('album', 'track_position'), ('album', 'track')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.performer', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='albums', through='music.AlbumTrack', to='music.track', verbose_name='Песни'),
        ),
    ]
